---
- hosts: dc1
  remote_user: fceller
  become: yes
  become_method: sudo

  tasks:

  - name: Stop ArangoDB cluster
    systemd:
      state: stopped
      name: arangodb3-cluster

  - name: Nuke ArangoDB cluster
    file:
      state: absent
      path: "/var/lib/arangodb3-cluster/"
